app:
  # Application Name.
  name: "E-mail auth"
  # Application URL.
  url: "http://127.0.0.1:8080/"
  # Target URL that will be shown after logging in.
  target: "http://127.0.0.1:8080/protected"
  # Address, where is HTTP server listening.
  bind: "127.0.0.1:8080"
  # Trust proxy X-Forwarded-For and X-Real-Ip headers.
  proxy: false

  # Allowed email addresses or domains (only @domain.org) to log in.
  emails:
  - "@test.com"
  # Path to a file, where additional emails are stored, deparated by newline.
  emails_file: ""

  # Users authentication using HTTP Basic Auth, with bcrypt hashes.
  # Generate entires using `htpasswd -Bbn username password`.
  # Use $$ to escape $ in password.
  users:
  - "username:$2y$05$jB7JXurhAS37c45mUwmvIO0vdLlzRVVlwJiQUY8eP2GL74TA5C0c2"
  # Path to a file, where additional users are stored, deparated by newline.
  # Generate file using `htpasswd -Bbn username password >> usersfile`.
  users_file: ""

  # Users or email addresses that are administrators.
  roles:
  - "admin@test.com=admin" # user = role
  - "admin=admin"
  # Path to a file, where additional roles are stored, deparated by newline.
  roles_file: ""

  # Allowed redirect URLs.
  redirect_allowlist:
  # Allow all HTTPs URLS.
  - "https://"
  # Allow specific host (any scheme).
  - "//127.0.0.1:8080"
  # Allow selected path prefix (any scheme and host).
  - "/foo-bar"
  # Allow scheme + path prefix with any host.
  - "http:///bar-foo"
  # Allow host + path prefix.
  - "//test.com/foo"

  # If login button should be shown, otherwise user is logged in automatically on visit.
  login_btn: true

  header:
    # If authentication header should be enabled.
    enabled: true
    # Authentication header name.
    name: "X-Auth-User"
    # Authentication header role.
    role: "X-Auth-Role"

  expiration:
    # Login link expiration in seconds. (default 5 min)
    link: 300
    # Session expiration in seconds. (default 14 days)
    session: 1209600

tmpl:
  # Template path for web page.
  page: "./tmpl/page.html"
  # Template path for email.
  email: "./tmpl/email.html"

email:
  # Email from address.
  from: "admin@localhost"
  # Email SMTP host.
  host: "127.0.0.1"
  # Email SMTP port.
  port: 25
  # Email SMTP username.
  username: ""
  # Email SMTP password.
  password: ""

cookie:
  # Cookie name.
  name: "MAILSESSION"
  # Associated domain with the cookie.
  domain: ""
  # A cookie with the Secure attribute is only sent to the server with an encrypted request over the HTTPS protocol.
  secure: true
  # A cookie with the HttpOnly attribute is inaccessible to the JavaScript Document.cookie API; it's only sent to the server.
  httponly: true

redis:
  # If redis should be used or not.
  enabled: false
  # Redis host.
  host: "127.0.0.1"
  # Redis port.
  port: 6379
  # Redis password.
  password: ""
  # Redis database.
  database: 0
